spring:
  profiles.active: local

---

spring:
  Profile: local

  mvc:
    static-path-pattern: /**

  datasource:
    url: jdbc:mysql://localhost:3306/db_bar_kushiage?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    content-type: text/html
    check-template-location: true

server:
  port: 8080

logging:
  config: classpath:logback-spring.xml

mybatis:
  configuration:
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml